version: "3"

services:
  db:
    image: mongo:latest
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
